[App]
Name = "challenge-wildfires-submission-deepMind"
Version = "1.1"
Title = "Wildfire Challenge Submission Title deepMind"
Description = "Wildfire Challenge Submission Description deepMind."
LongDescription = "about.md"
Tags = ["WILDFIRES"]

[Runtime]
Module = "src.app"
MemoryLimit = "5Gi"
MemoryReservation = "1Gi"
